# Site settings
title: Kimmie Lulu's Confections
description: > # this means to ignore newlines until "baseurl:"
   We Live and Love Cake, Cookies, Cupcakes...basically anything sweet! 🤗 
url: "http://yourdomain.com"
baseurl: ""
logo: Kimmie Lulu's <b>Confections</b>
paginate: 5
paginate_path: "/page:num/"
owner:
    email: KimmieLulusConfections@gmail.com
    facebook:
        show: true
        name: "Kimmie Lulu's Confections"
        url: "https://www.facebook.com/kimmielulusconfections/"
    github:
        show: true
        username: "kobakhit"
    twitter:
        show: false
        username: ""
    instagram:
        show: true
        username: "kimmielulus"
    disqus:
        show: false
        username: "ichihararifa"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate, jekyll-feed]