# Site settings
title: Kimmie Lulu's Confections
description: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
url: "http://yourdomain.com"
baseurl: ""
logo: Kimmie Lulu's <b>Confections</b>
paginate: 5
paginate_path: "/page:num/"
owner:
    email: KimmieLulusConfections@gmail.com
    facebook:
        show: true
        name: "Kimmie Lulu's Confections"
        url: "https://www.facebook.com/kimmielulusconfections/"
    github:
        show: true
        username: "kobakhit"
    twitter:
        show: false
        username: ""
    disqus:
        show: false
        username: "ichihararifa"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate, jekyll-feed]